### ISSUE TITLE
Cant open one recording in Phy

### ISSUE THREAD

**Issue by gregvoidman** [cortex-lab/KiloSort#257]
Hi,

I'm getting an error opening a recording in Phy that I have previously been able to open and  curate.

09:59:10.524 [E] __init__:62          An error has occurred (KeyError): 0
Traceback (most recent call last):
  File "/Users/AdamHarris/miniconda3/envs/phy/bin/phy", line 8, in <module>
    sys.exit(phycli())
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/apps/__init__.py", line 159, in cli_template_gui
    template_gui(params_path, **kwargs)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/apps/template/gui.py", line 217, in template_gui
    controller = TemplateController(model=model, dir_path=dir_path, **kwargs)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/apps/base.py", line 470, in __init__
    super(TemplateMixin, self).__init__(*args, **kwargs)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/apps/base.py", line 926, in __init__
    self._set_supervisor()
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/apps/template/gui.py", line 95, in _set_supervisor
    super(TemplateController, self)._set_supervisor()
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/apps/base.py", line 1017, in _set_supervisor
    context=self.context,
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/cluster/supervisor.py", line 637, in __init__
    spc = context.load('spikes_per_cluster') if context else None
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phy/utils/context.py", line 208, in load
    return load_pickle(path)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/phylib/utils/_misc.py", line 144, in load_pickle
    return load(path)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/Users/AdamHarris/miniconda3/envs/phy/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 0

Any ideas what the issue could be/how to resolve it? I am able to open other recordings without issue.

Many thanks!

**Comment by ChauhanT** [comment]
Hi @gregvoidman , I am getting similar errors. Were you able to fix this ? If so, any tips ? 

Thank you!
